--- 
- 
  commection: local
  hosts: switches
  tasks: 
    - 
      ios_command: 
        commands: "show version"
        provider: ""
        register: show_version
      name: "run show version"
    - 
      debug: var=show_version
      name: "print the show version output"
  vars: 
    cli: 
      host: ""
      password: ""
      username: ""
